language: node_js
node_js:
 — “7”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project recipeapp-8f558 — token 1/v_v8MoEHzh_BkET_Pl2hqnoZKuL95KEEB3ChnRz5Y5kpRA_R1dCwCNH9pXPeapEs